In [1]:
import numpy as np

In [2]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [3]:
#Read the train data
dataset_train=pd.read_csv('/home/sunil/Downloads/hacker earth compition/Dataset/train.csv')

In [4]:
dataset_train

,area_assesed,building_id,damage_grade,district_id,has_geotechnical_risk,has_geotechnical_risk_fault_crack,has_geotechnical_risk_flood,has_geotechnical_risk_land_settlement,has_geotechnical_risk_landslide,has_geotechnical_risk_liquefaction,has_geotechnical_risk_other,has_geotechnical_risk_rock_fall,has_repair_started,vdcmun_id
0,Both,24385bfd2a2,Grade 4,24,0.0,0,0,0,0,0,0,0,0.0,2489
1,Both,405d1bbebbf,Grade 2,44,0.0,0,0,0,0,0,0,0,1.0,4423
2,Both,351d9bc71f6,Grade 1,36,0.0,0,0,0,0,0,0,0,0.0,3650
3,Building removed,2be3a971166,Grade 5,30,0.0,0,0,0,0,0,0,0,0.0,3016
4,Both,34c7d073ea6,Grade 3,36,0.0,0,0,0,0,0,0,0,0.0,3627
5,Exterior,1f54965821f,Grade 5,21,0.0,0,0,0,0,0,0,0,0.0,2153
6,Both,2beb42eaeee,Grade 2,30,1.0,0,0,0,1,0,0,1,0.0,3018
7,Both,25e8adfd09a,Grade 5,26,0.0,0,0,0,0,0,0,0,0.0,2605
8,Both,1e96b58fa58,Grade 1,21,0.0,0,0,0,0,0,0,0,NaN,2102
9,Both,392cbd772c9,Grade 3,39,0.0,0,0,0,0,0,0,0,1.0,3929
10,Exterior,35074b0c35f,Grade 5,36,0.0,0,0,0,0,0,0,0,0.0,3644
11,Both,1ee123fa622,Grade 4,21,0.0,0,0,0,0,0,0,0,0.0,2122
12,Both,107560bc53d,Grade 2,11,0.0,0,0,0,0,0,0,0,1.0,1131
13,Building removed,355539e8f10,Grade 5,36,0.0,0,0,0,0,0,0,0,0.0,3665
14,Both,d49acbd60b,Grade 2,9,0.0,0,0,0,0,0,0,0,1.0,913
15,Both,28d9006c73e,Grade 5,28,0.0,0,0,0,0,0,0,0,0.0,2807
16,Both,2759f7a1e6f,Grade 4,27,0.0,0,0,0,0,0,0,0,1.0,2704
17,Both,27fd8b93119,Grade 3,27,0.0,0,0,0,0,0,0,0,0.0,2748
18,Both,27597222066,Grade 4,27,0.0,0,0,0,0,0,0,0,1.0,2704
19,Exterior,1b9136a5a0af,Grade 3,30,0.0,0,0,0,0,0,0,0,0.0,3031
20,Both,122d2f8638e,Grade 4,12,0.0,0,0,0,0,0,0,0,0.0,1249
21,Both,25e8fa2ee5a,Grade 4,26,0.0,0,0,0,0,0,0,0,0.0,2605
22,Both,366c9f7bc37,Grade 4,37,0.0,0,0,0,0,0,0,0,1.0,3740
23,Building removed,4372e823ef3,Grade 5,46,1.0,1,0,0,1,0,0,0,1.0,4635
24,Both,2c1404219eb,Grade 4,30,0.0,0,0,0,0,0,0,0,0.0,3029
25,Both,2425e1c30ef,Grade 3,24,0.0,0,0,0,0,0,0,0,0.0,2484
26,Building removed,1d7b8343e6a,Grade 5,20,0.0,0,0,0,0,0,0,0,0.0,2026
27,Building removed,1f45e8dec7e,Grade 5,21,1.0,0,0,0,1,0,0,0,0.0,2149
28,Building removed,2c08cd8e16e,Grade 5,30,0.0,0,0,0,0,0,0,0,0.0,3026
29,Building removed,2a55346ebd2,Grade 5,29,0.0,0,0,0,0,0,0,0,0.0,2909
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631731,Both,2367b4afcec,Grade 3,24,0.0,0,0,0,0,0,0,0,1.0,2433
631732,Both,2c538845973,Grade 4,30,0.0,0,0,0,0,0,0,0,0.0,3046
631733,Both,28e803bcd53,Grade 4,28,0.0,0,0,0,0,0,0,0,0.0,2811
631734,Not able to inspect,223281b865a,Grade 5,23,1.0,1,0,0,0,0,0,0,0.0,2350
631735,Building removed,2c5acbeee22,Grade 5,30,0.0,0,0,0,0,0,0,0,0.0,3048
631736,Both,1d4b32174f3,Grade 3,20,1.0,0,0,1,0,0,0,0,1.0,2013
631737,Exterior,21b3f569646,Grade 5,23,0.0,0,0,0,0,0,0,0,0.0,2316
631738,Exterior,234a03e6dae,Grade 5,24,0.0,0,0,0,0,0,0,0,0.0,2425
631739,Both,37d62009f0a,Grade 2,38,0.0,0,0,0,0,0,0,0,1.0,3837
631740,Both,25d98e2adb6,Grade 3,26,0.0,0,0,0,0,0,0,0,0.0,2601
631741,Both,1d780c736a4,Grade 3,20,0.0,0,0,0,0,0,0,0,1.0,2025
631742,Building removed,2980ad4d91b,Grade 5,28,0.0,0,0,0,0,0,0,0,0.0,2852
631743,Not able to inspect,2a769ee37c8,Grade 5,29,1.0,0,1,0,1,0,0,0,0.0,2918
631744,Building removed,2098dfb0db6,Grade 5,22,0.0,0,0,0,0,0,0,0,0.0,2240
631745,Not able to inspect,200b6324b32,Grade 5,22,0.0,0,0,0,0,0,0,0,0.0,2202
631746,Building removed,225b7c23cec,Grade 5,23,1.0,1,0,0,0,0,0,0,0.0,2361
631747,Exterior,3ad9429f5d9,Grade 2,40,0.0,0,0,0,0,0,0,0,0.0,4044
631748,Exterior,16bf41e481e7,Grade 4,25,0.0,0,0,0,0,0,0,0,0.0,2501
631749,Exterior,34d6ad99271,Grade 5,36,0.0,0,0,0,0,0,0,0,0.0,3631
631750,Building removed,25f05aaa24a,Grade 5,26,0.0,0,0,0,0,0,0,0,0.0,2607
631751,Building removed,2c17f703e5f,Grade 5,30,0.0,0,0,0,0,0,0,0,0.0,3030
631752,Both,15723769326e,Grade 5,23,0.0,0,0,0,0,0,0,0,0.0,2358
631753,Both,1f02dab9eae,Grade 4,21,0.0,0,0,0,0,0,0,0,0.0,2131
631754,Exterior,1f2baeff11b,Grade 3,21,0.0,0,0,0,0,0,0,0,0.0,2142
631755,Both,23def3d0829,Grade 1,24,0.0,0,0,0,0,0,0,0,NaN,2465
631756,Both,12471d178ea,Grade 4,12,0.0,0,0,0,0,0,0,0,0.0,1256
631757,Exterior,233af710f9a,Grade 5,24,0.0,0,0,0,0,0,0,0,0.0,2421
631758,Both,37fb442badd,Grade 2,38,0.0,0,0,0,0,0,0,0,1.0,3847
631759,Exterior,2c0906c86f0,Grade 4,30,0.0,0,0,0,0,0,0,0,0.0,3026
631760,Both,293272232cf,Grade 2,28,0.0,0,0,0,0,0,0,0,0.0,2831

In [6]:
#store the damage_grade into another variable
A=dataset_train['damage_grade']

In [7]:
y_train=np_utils.to_categorical(A)

0         Grade 4
1         Grade 2
2         Grade 1
3         Grade 5
4         Grade 3
5         Grade 5
6         Grade 2
7         Grade 5
8         Grade 1
9         Grade 3
10        Grade 5
11        Grade 4
12        Grade 2
13        Grade 5
14        Grade 2
15        Grade 5
16        Grade 4
17        Grade 3
18        Grade 4
19        Grade 3
20        Grade 4
21        Grade 4
22        Grade 4
23        Grade 5
24        Grade 4
25        Grade 3
26        Grade 5
27        Grade 5
28        Grade 5
29        Grade 5
           ...
631731    Grade 3
631732    Grade 4
631733    Grade 4
631734    Grade 5
631735    Grade 5
631736    Grade 3
631737    Grade 5
631738    Grade 5
631739    Grade 2
631740    Grade 3
631741    Grade 3
631742    Grade 5
631743    Grade 5
631744    Grade 5
631745    Grade 5
631746    Grade 5
631747    Grade 2
631748    Grade 4
631749    Grade 5
631750    Grade 5
631751    Grade 5
631752    Grade 5
631753    Grade 4
631754    Grade 3
631755    Grade 1
631756    Grade 4
631757    Grade 5
631758    Grade 2
631759    Grade 4
631760    Grade 2
Name: damage_grade, Length: 631761, dtype: object

In [56]:
#labelEncoder of A
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
A=le.fit_transform(A)

In [57]:
pd.DataFrame(A)

        0
0       3
1       1
2       0
3       4
4       2
5       4
6       1
7       4
8       0
9       2
10      4
11      3
12      1
13      4
14      1
15      4
16      3
17      2
18      3
19      2
20      3
21      3
22      3
23      4
24      3
25      2
26      4
27      4
28      4
29      4
...    ..
631731  2
631732  3
631733  3
631734  4
631735  4
631736  2
631737  4
631738  4
631739  1
631740  2
631741  2
631742  4
631743  4
631744  4
631745  4
631746  4
631747  1
631748  3
631749  4
631750  4
631751  4
631752  4
631753  3
631754  2
631755  0
631756  3
631757  4
631758  1
631759  3
631760  1

[631761 rows x 1 columns]

In [58]:
# delete the Damage_grade from train_dataset
del dataset_train['damage_grade']

In [59]:
dataset_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 631761 entries, 0 to 631760
Data columns (total 13 columns):
area_assesed                             631761 non-null object
building_id                              631761 non-null object
district_id                              631761 non-null int64
has_geotechnical_risk                    631761 non-null float64
has_geotechnical_risk_fault_crack        631761 non-null int64
has_geotechnical_risk_flood              631761 non-null int64
has_geotechnical_risk_land_settlement    631761 non-null int64
has_geotechnical_risk_landslide          631761 non-null int64
has_geotechnical_risk_liquefaction       631761 non-null int64
has_geotechnical_risk_other              631761 non-null int64
has_geotechnical_risk_rock_fall          631761 non-null int64
has_repair_started                       598344 non-null float64
vdcmun_id                                631761 non-null int64
dtypes: float64(2), int64(9), object(2)
memory usage: 62.7+ MB

In [60]:
#Read the test data
dataset_test=pd.read_csv('/home/sunil/Downloads/hacker earth compition/Dataset/test.csv')

In [61]:
dataset_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421175 entries, 0 to 421174
Data columns (total 13 columns):
area_assesed                             421175 non-null object
building_id                              421175 non-null object
district_id                              421175 non-null int64
has_geotechnical_risk                    421175 non-null float64
has_geotechnical_risk_fault_crack        421175 non-null int64
has_geotechnical_risk_flood              421175 non-null int64
has_geotechnical_risk_land_settlement    421175 non-null int64
has_geotechnical_risk_landslide          421175 non-null int64
has_geotechnical_risk_liquefaction       421175 non-null int64
has_geotechnical_risk_other              421175 non-null int64
has_geotechnical_risk_rock_fall          421175 non-null int64
has_repair_started                       399253 non-null float64
vdcmun_id                                421175 non-null int64
dtypes: float64(2), int64(9), object(2)
memory usage: 41.8+ MB

In [62]:
#B=dataset_test["building_id"]

In [13]:
# combined the both data of train & test store the into another variable
All_data=[dataset_train,dataset_test]

In [14]:
 All_data1=pd.concat(All_data)

In [15]:
All_data1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1052936 entries, 0 to 421174
Data columns (total 13 columns):
area_assesed                             1052936 non-null object
building_id                              1052936 non-null object
district_id                              1052936 non-null int64
has_geotechnical_risk                    1052936 non-null float64
has_geotechnical_risk_fault_crack        1052936 non-null int64
has_geotechnical_risk_flood              1052936 non-null int64
has_geotechnical_risk_land_settlement    1052936 non-null int64
has_geotechnical_risk_landslide          1052936 non-null int64
has_geotechnical_risk_liquefaction       1052936 non-null int64
has_geotechnical_risk_other              1052936 non-null int64
has_geotechnical_risk_rock_fall          1052936 non-null int64
has_repair_started                       997597 non-null float64
vdcmun_id                                1052936 non-null int64
dtypes: float64(2), int64(9), object(2)
memory usage: 112.5+ MB

In [16]:
#filling the missing value of has_repair_started
means=All_data1["has_repair_started"].mean()
All_data1["has_repair_started"].fillna(means,inplace=True)
means
All_data1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1052936 entries, 0 to 421174
Data columns (total 13 columns):
area_assesed                             1052936 non-null object
building_id                              1052936 non-null object
district_id                              1052936 non-null int64
has_geotechnical_risk                    1052936 non-null float64
has_geotechnical_risk_fault_crack        1052936 non-null int64
has_geotechnical_risk_flood              1052936 non-null int64
has_geotechnical_risk_land_settlement    1052936 non-null int64
has_geotechnical_risk_landslide          1052936 non-null int64
has_geotechnical_risk_liquefaction       1052936 non-null int64
has_geotechnical_risk_other              1052936 non-null int64
has_geotechnical_risk_rock_fall          1052936 non-null int64
has_repair_started                       1052936 non-null float64
vdcmun_id                                1052936 non-null int64
dtypes: float64(2), int64(9), object(2)
memory usage: 112.5+ MB

In [17]:
b= All_data1['building_id']

In [18]:
del All_data1["building_id"]

In [19]:
# select the object Data
obj_df=All_data1.select_dtypes(include=['object'])
obj_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1052936 entries, 0 to 421174
Data columns (total 1 columns):
area_assesed    1052936 non-null object
dtypes: object(1)
memory usage: 16.1+ MB

In [20]:
#dummmies the object data
obj_df_dummies=pd.get_dummies(obj_df)

In [21]:
type(obj_df_dummies)

pandas.core.frame.DataFrame

In [22]:
del All_data1['area_assesed']

In [23]:
type(All_data1)

pandas.core.frame.DataFrame

In [24]:
All_data1=pd.concat([ All_data1,obj_df_dummies],axis=1)

In [25]:
All_data1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1052936 entries, 0 to 421174
Data columns (total 16 columns):
district_id                              1052936 non-null int64
has_geotechnical_risk                    1052936 non-null float64
has_geotechnical_risk_fault_crack        1052936 non-null int64
has_geotechnical_risk_flood              1052936 non-null int64
has_geotechnical_risk_land_settlement    1052936 non-null int64
has_geotechnical_risk_landslide          1052936 non-null int64
has_geotechnical_risk_liquefaction       1052936 non-null int64
has_geotechnical_risk_other              1052936 non-null int64
has_geotechnical_risk_rock_fall          1052936 non-null int64
has_repair_started                       1052936 non-null float64
vdcmun_id                                1052936 non-null int64
area_assesed_Both                        1052936 non-null uint8
area_assesed_Building removed            1052936 non-null uint8
area_assesed_Exterior                    1052936 non-null uint8
area_assesed_Interior                    1052936 non-null uint8
area_assesed_Not able to inspect         1052936 non-null uint8
dtypes: float64(2), int64(9), uint8(5)
memory usage: 101.4 MB

In [26]:
#split data into train data
X_train=All_data1[0:631761]

In [27]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 631761 entries, 0 to 631760
Data columns (total 16 columns):
district_id                              631761 non-null int64
has_geotechnical_risk                    631761 non-null float64
has_geotechnical_risk_fault_crack        631761 non-null int64
has_geotechnical_risk_flood              631761 non-null int64
has_geotechnical_risk_land_settlement    631761 non-null int64
has_geotechnical_risk_landslide          631761 non-null int64
has_geotechnical_risk_liquefaction       631761 non-null int64
has_geotechnical_risk_other              631761 non-null int64
has_geotechnical_risk_rock_fall          631761 non-null int64
has_repair_started                       631761 non-null float64
vdcmun_id                                631761 non-null int64
area_assesed_Both                        631761 non-null uint8
area_assesed_Building removed            631761 non-null uint8
area_assesed_Exterior                    631761 non-null uint8
area_assesed_Interior                    631761 non-null uint8
area_assesed_Not able to inspect         631761 non-null uint8
dtypes: float64(2), int64(9), uint8(5)
memory usage: 60.9 MB

In [28]:
#split data into test data
X_test=All_data1[631761:]

In [29]:
b=pd.DataFrame(b)

In [30]:
c1=b.iloc[631761:,:]

In [31]:
c1

         building_id
0         a3380c4f75
1         a338a4e653
2         a338a4e6b7
3         a33a6eaa3a
4         a33b073ff6
5        6604e4896c6
6         a33b07430f
7         a33c386cf3
8         a33c386ee7
9         a33c38700f
10        a33c387079
11       6627e911d56
12        a3730e8420
13        a373a71a3d
14        a3743fb055
15        a3743fb121
16        a374d84676
17        a374d848cb
18        a374d8492a
19        a37570ddbe
20        a376097504
21        a3760975cd
22        a3aea94dbf
23        a376a209ee
24        a376a20b1e
25        a376a20b83
26        a3773aa0da
27        a3b1a441bd
28        a3773aa19c
29        a3773aa2ca
...              ...
421145   355cf98de6a
421146   355cf98df96
421147   355cf98e1ef
421148   355cf98e2ba
421149   355cf98e321
421150  215a1bf8eac6
421151   355cf98e4af
421152  215a1bf8f67f
421153   355cf98e63d
421154   355cf98e6a3
421155   355cf98e705
421156   355cf98e76d
421157   355cf98e960
421158   355cf98e9c3
421159   355cf98eb51
421160   355cf98ec1c
421161   355cf98ed43
421162   355cf98eda8
421163   355cf98ee0a
421164   355cf98ef37
421165  215a1bf95c0f
421166   355cf98f0cc
421167   355cf98f257
421168   355cf98f2c2
421169  215a1bf97f36
421170   355cf98f382
421171   355cf98f44b
421172   355cf98f577
421173  215a1bf9ae16
421174  215a1bf9b9ce

[421175 rows x 1 columns]

In [32]:
c1=pd.DataFrame(c1)

In [33]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 421175 entries, 0 to 421174
Data columns (total 16 columns):
district_id                              421175 non-null int64
has_geotechnical_risk                    421175 non-null float64
has_geotechnical_risk_fault_crack        421175 non-null int64
has_geotechnical_risk_flood              421175 non-null int64
has_geotechnical_risk_land_settlement    421175 non-null int64
has_geotechnical_risk_landslide          421175 non-null int64
has_geotechnical_risk_liquefaction       421175 non-null int64
has_geotechnical_risk_other              421175 non-null int64
has_geotechnical_risk_rock_fall          421175 non-null int64
has_repair_started                       421175 non-null float64
vdcmun_id                                421175 non-null int64
area_assesed_Both                        421175 non-null uint8
area_assesed_Building removed            421175 non-null uint8
area_assesed_Exterior                    421175 non-null uint8
area_assesed_Interior                    421175 non-null uint8
area_assesed_Not able to inspect         421175 non-null uint8
dtypes: float64(2), int64(9), uint8(5)
memory usage: 40.6 MB

# DecisionTreeClassifier

In [36]:
 from sklearn.tree import DecisionTreeRegressor
regressor1=DecisionTreeRegressor(random_state=42)
regressor1.fit(X_train,A)
regressor1.score(X_train,A)

0.742805972351651

# RandomForestRegressor

In [41]:
from sklearn.ensemble import RandomForestRegressor,BaggingClassifier,AdaBoostClassifier,VotingClassifier,RandomForestClassifier
reeg=RandomForestRegressor(n_estimators=20,random_state=0)
reeg.fit(X_train,A)
reeg.score(X_train,A)

0.7416720398189754

# BaggingClassifier

In [38]:
bg=BaggingClassifier(DecisionTreeClassifier(),max_samples=0.5,max_features=1.0,n_estimators=20)
bg.fit(X_train,A)
bg.score(X_train,A)

0.6803886279779854

# AdaBoostClassifier

In [39]:
Adg=AdaBoostClassifier(DecisionTreeClassifier(),n_estimators=10,learning_rate=1)
Adg.fit(X_train,A) 
Adg.score(X_train,A)

0.6818559550209652

# VotingClassifier

In [42]:
dt=DecisionTreeClassifier()
re=RandomForestClassifier(n_estimators=20,random_state=0)
evc=VotingClassifier(estimators=[('re',re),('dt',dt)],voting='hard')
evc.fit(X_train,A)
evc.score(X_train,A)

/home/sunil/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

0.6818765324228624

In [46]:
building_structure=pd.read_csv('/home/sunil/Downloads/hacker earth compition/Dataset/Building_Structure.csv')

In [47]:
building_ownership=pd.read_csv('/home/sunil/Downloads/hacker earth compition/Dataset/Building_Ownership_Use.csv')

In [64]:


result = pd.merge(building_structure, building_ownership, on='building_id')
res_train=pd.merge(dataset_train,result,on="building_id")
res_test=pd.merge(dataset_train,result,on="building_id")

In [65]:
res_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 631761 entries, 0 to 631760
Data columns (total 57 columns):
area_assesed                              631761 non-null object
building_id                               631761 non-null object
district_id                               631761 non-null int64
has_geotechnical_risk                     631761 non-null float64
has_geotechnical_risk_fault_crack         631761 non-null int64
has_geotechnical_risk_flood               631761 non-null int64
has_geotechnical_risk_land_settlement     631761 non-null int64
has_geotechnical_risk_landslide           631761 non-null int64
has_geotechnical_risk_liquefaction        631761 non-null int64
has_geotechnical_risk_other               631761 non-null int64
has_geotechnical_risk_rock_fall           631761 non-null int64
has_repair_started                        598344 non-null float64
vdcmun_id                                 631761 non-null int64
district_id_x                             631761 non-null int64
vdcmun_id_x                               631761 non-null int64
ward_id_x                                 631761 non-null int64
count_floors_pre_eq                       631761 non-null int64
count_floors_post_eq                      631761 non-null int64
age_building                              631761 non-null int64
plinth_area_sq_ft                         631761 non-null int64
height_ft_pre_eq                          631761 non-null int64
height_ft_post_eq                         631761 non-null int64
land_surface_condition                    631761 non-null object
foundation_type                           631761 non-null object
roof_type                                 631761 non-null object
ground_floor_type                         631761 non-null object
other_floor_type                          631761 non-null object
position                                  631761 non-null object
plan_configuration                        631761 non-null object
has_superstructure_adobe_mud              631761 non-null int64
has_superstructure_mud_mortar_stone       631761 non-null int64
has_superstructure_stone_flag             631761 non-null int64
has_superstructure_cement_mortar_stone    631761 non-null int64
has_superstructure_mud_mortar_brick       631761 non-null int64
has_superstructure_cement_mortar_brick    631761 non-null int64
has_superstructure_timber                 631761 non-null int64
has_superstructure_bamboo                 631761 non-null int64
has_superstructure_rc_non_engineered      631761 non-null int64
has_superstructure_rc_engineered          631761 non-null int64
has_superstructure_other                  631761 non-null int64
condition_post_eq                         631761 non-null object
district_id_y                             631761 non-null int64
vdcmun_id_y                               631761 non-null int64
ward_id_y                                 631761 non-null int64
legal_ownership_status                    631761 non-null object
count_families                            631760 non-null float64
has_secondary_use                         631761 non-null float64
has_secondary_use_agriculture             631761 non-null int64
has_secondary_use_hotel                   631761 non-null int64
has_secondary_use_rental                  631761 non-null int64
has_secondary_use_institution             631761 non-null int64
has_secondary_use_school                  631761 non-null int64
has_secondary_use_industry                631761 non-null int64
has_secondary_use_health_post             631761 non-null int64
has_secondary_use_gov_office              631761 non-null int64
has_secondary_use_use_police              631761 non-null int64
has_secondary_use_other                   631761 non-null int64
dtypes: float64(4), int64(42), object(11)
memory usage: 279.6+ MB

In [66]:
res_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 631761 entries, 0 to 631760
Data columns (total 57 columns):
area_assesed                              631761 non-null object
building_id                               631761 non-null object
district_id                               631761 non-null int64
has_geotechnical_risk                     631761 non-null float64
has_geotechnical_risk_fault_crack         631761 non-null int64
has_geotechnical_risk_flood               631761 non-null int64
has_geotechnical_risk_land_settlement     631761 non-null int64
has_geotechnical_risk_landslide           631761 non-null int64
has_geotechnical_risk_liquefaction        631761 non-null int64
has_geotechnical_risk_other               631761 non-null int64
has_geotechnical_risk_rock_fall           631761 non-null int64
has_repair_started                        598344 non-null float64
vdcmun_id                                 631761 non-null int64
district_id_x                             631761 non-null int64
vdcmun_id_x                               631761 non-null int64
ward_id_x                                 631761 non-null int64
count_floors_pre_eq                       631761 non-null int64
count_floors_post_eq                      631761 non-null int64
age_building                              631761 non-null int64
plinth_area_sq_ft                         631761 non-null int64
height_ft_pre_eq                          631761 non-null int64
height_ft_post_eq                         631761 non-null int64
land_surface_condition                    631761 non-null object
foundation_type                           631761 non-null object
roof_type                                 631761 non-null object
ground_floor_type                         631761 non-null object
other_floor_type                          631761 non-null object
position                                  631761 non-null object
plan_configuration                        631761 non-null object
has_superstructure_adobe_mud              631761 non-null int64
has_superstructure_mud_mortar_stone       631761 non-null int64
has_superstructure_stone_flag             631761 non-null int64
has_superstructure_cement_mortar_stone    631761 non-null int64
has_superstructure_mud_mortar_brick       631761 non-null int64
has_superstructure_cement_mortar_brick    631761 non-null int64
has_superstructure_timber                 631761 non-null int64
has_superstructure_bamboo                 631761 non-null int64
has_superstructure_rc_non_engineered      631761 non-null int64
has_superstructure_rc_engineered          631761 non-null int64
has_superstructure_other                  631761 non-null int64
condition_post_eq                         631761 non-null object
district_id_y                             631761 non-null int64
vdcmun_id_y                               631761 non-null int64
ward_id_y                                 631761 non-null int64
legal_ownership_status                    631761 non-null object
count_families                            631760 non-null float64
has_secondary_use                         631761 non-null float64
has_secondary_use_agriculture             631761 non-null int64
has_secondary_use_hotel                   631761 non-null int64
has_secondary_use_rental                  631761 non-null int64
has_secondary_use_institution             631761 non-null int64
has_secondary_use_school                  631761 non-null int64
has_secondary_use_industry                631761 non-null int64
has_secondary_use_health_post             631761 non-null int64
has_secondary_use_gov_office              631761 non-null int64
has_secondary_use_use_police              631761 non-null int64
has_secondary_use_other                   631761 non-null int64
dtypes: float64(4), int64(42), object(11)
memory usage: 279.6+ MB

# predict of DecisionTreeClass

In [52]:
y_pred=regressor1.predict(X_test)
y_pred=pd.DataFrame(y_pred)
y_pred=np.round(y_pred)
pd.DataFrame(y_pred)

          0
0       2.0
1       2.0
2       4.0
3       2.0
4       4.0
5       3.0
6       2.0
7       4.0
8       2.0
9       2.0
10      2.0
11      2.0
12      2.0
13      2.0
14      2.0
15      2.0
16      2.0
17      2.0
18      2.0
19      2.0
20      2.0
21      2.0
22      2.0
23      2.0
24      4.0
25      2.0
26      2.0
27      4.0
28      2.0
29      2.0
...     ...
421145  4.0
421146  4.0
421147  4.0
421148  4.0
421149  4.0
421150  4.0
421151  4.0
421152  4.0
421153  4.0
421154  4.0
421155  4.0
421156  4.0
421157  4.0
421158  3.0
421159  4.0
421160  4.0
421161  4.0
421162  4.0
421163  4.0
421164  4.0
421165  0.0
421166  4.0
421167  4.0
421168  4.0
421169  4.0
421170  4.0
421171  4.0
421172  0.0
421173  4.0
421174  4.0

[421175 rows x 1 columns]

In [53]:
y_pred.info()
y_pred[0].value_counts()
y_pred=y_pred.rename(columns={0:'damage_grade'})

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421175 entries, 0 to 421174
Data columns (total 1 columns):
0    421175 non-null float64
dtypes: float64(1)
memory usage: 3.2 MB

In [54]:
y_pred.damage_grade.replace([0.0,1.0,2.0,3.0,4.0], ['Grade 1','Grade 2','Grade 3','Grade 4','Grade 5'], inplace=True)
y_pred.head()
file=pd.concat([c1,y_pred],axis=1)

In [55]:
null_columns=y_pred.columns[y_pred.isnull().any()]
y_pred[null_columns].isnull().sum()

Series([], dtype: float64)

In [56]:
file=pd.DataFrame(file)

In [57]:
file.to_csv('122.csv',index=False)

In [42]:
#prediction = pd.DataFrame(file.to_csv('hacker_earth prediction14.csv',index=False) )

In [43]:
null_columns=y_pred.columns[y_pred.isnull().any()]
y_pred[null_columns].isnull().sum()

Series([], dtype: float64)

In [58]:
file

         building_id damage_grade
0         a3380c4f75      Grade 3
1         a338a4e653      Grade 3
2         a338a4e6b7      Grade 5
3         a33a6eaa3a      Grade 3
4         a33b073ff6      Grade 5
5        6604e4896c6      Grade 4
6         a33b07430f      Grade 3
7         a33c386cf3      Grade 5
8         a33c386ee7      Grade 3
9         a33c38700f      Grade 3
10        a33c387079      Grade 3
11       6627e911d56      Grade 3
12        a3730e8420      Grade 3
13        a373a71a3d      Grade 3
14        a3743fb055      Grade 3
15        a3743fb121      Grade 3
16        a374d84676      Grade 3
17        a374d848cb      Grade 3
18        a374d8492a      Grade 3
19        a37570ddbe      Grade 3
20        a376097504      Grade 3
21        a3760975cd      Grade 3
22        a3aea94dbf      Grade 3
23        a376a209ee      Grade 3
24        a376a20b1e      Grade 5
25        a376a20b83      Grade 3
26        a3773aa0da      Grade 3
27        a3b1a441bd      Grade 5
28        a3773aa19c      Grade 3
29        a3773aa2ca      Grade 3
...              ...          ...
421145   355cf98de6a      Grade 5
421146   355cf98df96      Grade 5
421147   355cf98e1ef      Grade 5
421148   355cf98e2ba      Grade 5
421149   355cf98e321      Grade 5
421150  215a1bf8eac6      Grade 5
421151   355cf98e4af      Grade 5
421152  215a1bf8f67f      Grade 5
421153   355cf98e63d      Grade 5
421154   355cf98e6a3      Grade 5
421155   355cf98e705      Grade 5
421156   355cf98e76d      Grade 5
421157   355cf98e960      Grade 5
421158   355cf98e9c3      Grade 4
421159   355cf98eb51      Grade 5
421160   355cf98ec1c      Grade 5
421161   355cf98ed43      Grade 5
421162   355cf98eda8      Grade 5
421163   355cf98ee0a      Grade 5
421164   355cf98ef37      Grade 5
421165  215a1bf95c0f      Grade 1
421166   355cf98f0cc      Grade 5
421167   355cf98f257      Grade 5
421168   355cf98f2c2      Grade 5
421169  215a1bf97f36      Grade 5
421170   355cf98f382      Grade 5
421171   355cf98f44b      Grade 5
421172   355cf98f577      Grade 1
421173  215a1bf9ae16      Grade 5
421174  215a1bf9b9ce      Grade 5

[421175 rows x 2 columns]